services:
  mongo:
    image: mongo:7.0
    container_name: inventory-mongo
    ports:
      - "27017:27017"
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.runCommand({ ping: 1 })"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - mongo_data:/data/db

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: inventory-app
    environment:
      - MONGODB_URL=mongodb://mongo:27017
      - MONGODB_DB=inventory_db
    # depends_on:
    #   mongo:
    #     condition: service_healthy
    ports:
      - "8000:8000"
    command: ["poetry", "run", "uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000"]

volumes:
  mongo_data:
    driver: local
